### ISSUE TITLE
Help required to run the code with Egogesture dataset

### ISSUE THREAD

**Issue by ghost** [ahmetgunduz/Real-time-GesRec#108]
Hello @ahmetgunduz,

Is there any way I could get help on step by step guide to see how could I run this code with only EgoGesure Dataset? 
I downloaded the whole code and Egogesture dataset, Ran the steps mentioned in the README file for Egogesture Preparation but I could not able to run the main.py. I'm using spyder IDE in Windows+GPU.

I'm having an error as:
Traceback (most recent call last):
File "C:\Users\PRASH\Project_3D_design\Real-time-GesRec-master\main.py", line 98, in
train_loader = torch.utils.data.DataLoader(
File "C:\Users\PRASH\anaconda3\envs\user_interface\lib\site-packages\torch\utils\data\dataloader.py", line 351, in init
sampler = RandomSampler(dataset, generator=generator) # type: ignore[arg-type]
File "C:\Users\PRASH\anaconda3\envs\user_interface\lib\site-packages\torch\utils\data\sampler.py", line 107, in init
raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

(user_interface) C:\Users\PRASH\Project_3D_design\Real-time-GesRec-master>

**Comment by Alex350123** [comment]
> Hello @ahmetgunduz,
> 
> Is there any way I could get help on step by step guide to see how could I run this code with only EgoGesure Dataset? I downloaded the whole code and Egogesture dataset, Ran the steps mentioned in the README file for Egogesture Preparation but I could not able to run the main.py. I'm using spyder IDE in Windows+GPU.
> 
> I'm having an error as: Traceback (most recent call last): File "C:\Users\PRASH\Project_3D_design\Real-time-GesRec-master\main.py", line 98, in train_loader = torch.utils.data.DataLoader( File "C:\Users\PRASH\anaconda3\envs\user_interface\lib\site-packages\torch\utils\data\dataloader.py", line 351, in init sampler = RandomSampler(dataset, generator=generator) # type: ignore[arg-type] File "C:\Users\PRASH\anaconda3\envs\user_interface\lib\site-packages\torch\utils\data\sampler.py", line 107, in init raise ValueError("num_samples should be a positive integer " ValueError: num_samples should be a positive integer value, but got num_samples=0
> 
> (user_interface) C:\Users\PRASH\Project_3D_design\Real-time-GesRec-master>

Hello. I met the same problem here with this ValueError. May I know how it went with you and how you fix it?
