### ISSUE TITLE
cuda gpu device Error

### ISSUE THREAD

**Issue by parkjh688** [ahmetgunduz/Real-time-GesRec#33]
Hi.

I have 1 GPU in my computer but I got this error.
I'm newbie of Pytorch so I don't know this Error's meaning.

```
Traceback (most recent call last):
  File "main.py", line 177, in <module>
    train_logger, train_batch_logger)
  File "/home/eden/Real-time-GesRec/train.py", line 34, in train_epoch
    outputs = model(inputs)
  File "/home/eden/anaconda3/envs/gesrec/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eden/anaconda3/envs/gesrec/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 146, in forward
    "them on device: {}".format(self.src_device_obj, t.device))
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu

```

**Comment by parkjh688** [comment]
I found the reason of error.

When I print `t.device` and `self.src_device_obj` in torch *data_parallel.py* file.
I got cpu for t.device and cuda:0 for self.src_device_obj.

I guess the model made for CPU version. Can you tell me how to change CPU to GPU version?

**Comment by ahmetgunduz** [comment]
The models are made for GPU actually. Which version of torch are you using? Are you sure that you are using GPU? You can check it as in  https://stackoverflow.com/a/48152675/6400484

**Comment by parkjh688** [comment]
Yes I have and I checked it again by using that link.

![image](https://user-images.githubusercontent.com/36429399/62756298-23dad600-bab2-11e9-90ee-a656c1e006c6.png)

**Comment by ahmetgunduz** [comment]
It seems to be a pytorch bug, Please check this solution https://discuss.pytorch.org/t/bug-in-dataparallel-only-works-if-the-dataset-device-is-cuda-0/28634/18

**Comment by Karthik-Bhaskar** [comment]
Hi,

@ahmetgunduz Even I am facing the same issue. Is there any solution for this ? 

I checked if torch is able to detect the cuda device (1 GPU in my case), It seems good. I am using the torch version 1.2.

![Screenshot from 2019-08-22 13-22-14](https://user-images.githubusercontent.com/13200370/63759136-47c55680-c8bd-11e9-874b-d2bd3100e74c.png)

@parkjh688 were you able to solve the issue ?

Thanks in advance.

**Comment by ahmetgunduz** [comment]
@Karthik-Bhaskar just to check can you please add `--no_cuda` parameter as well if it is working with cpu.

**Comment by Karthik-Bhaskar** [comment]
Should I need to add any value for `--no_cuda` parameter like True or False. 

Or just include without any value like this,

```
#!/bin/bash
python offline_test.py \
--root_path ~/ \
--video_path /home/karthik/Desktop/Data/Jester/20bn-jester-v1 \
--annotation_path Desktop/Project/Real-time-GesRec/annotation_Jester/jester.json \
--result_path Desktop/Project/Real-time-GesRec/results \
--resume_path Desktop/Project/Real-time-GesRec/pre-trained-models/jester_resnext_101_RGB_32.pth \
--dataset jester \
--sample_duration 32 \
--learning_rate 0.01 \
--model resnext \
--model_depth 101 \
--batch_size 1 \
--n_classes 27 \
--n_finetune_classes 27 \
--modality RGB \
--n_threads 8 \
--checkpoint 1 \
--train_crop random \
--n_val_samples 1 \
--test_subset val \
--n_epochs 100 \
--no_cuda
```

I tried executing with the above parameters and ran into 
`RuntimeError: Error(s) in loading state_dict for ResNeXt`

Please tell me if it's the wrong way to add that parameter.

Thanks.

**Comment by ahmetgunduz** [comment]
Everything looks fine actually. The way you gave `no_cuda` parameter is right. 
Honestly, I have no clue about the error. It may be because of the torch version, the repo is lastly updated for PyTorch 1.0.1.post2 maybe you can downgrade your pytorch version and try.

**Comment by Karthik-Bhaskar** [comment]
I downgraded the PyTorch to 1.0.1.post2 but the issue remains the same. Can you please let me know if I need to use any particular version of the package or library. Currently, I am using Python 3.6 and Cuda 10.

**Comment by ahmetgunduz** [comment]
python 3.7.3 and Cuda 10 is the current versions I am using. See below:
<img width="282" alt="Screen Shot 2019-08-31 at 15 56 29" src="https://user-images.githubusercontent.com/16335853/64064301-3a370600-cc08-11e9-8c4f-473e2e9b7bdc.png">

**Comment by parkjh688** [comment]
@ahmetgunduz Unfortunately not yet. I will try to run this code with other machine which has another cuda and cudnn version next week to check this problem whether cuda problem or not.
But I guess this looks like cuda version problem.

**Comment by ahmetgunduz** [comment]
@parkjh688 That is great! Looking forward to seeing the outcome...

**Comment by xiaomingnio** [comment]
model, parameters = generate_model(opt)
model = model.cuda()

 Add the sentence above.

**Comment by MrXuf** [comment]
@Karthik-Bhaskar  were you able to solve the issue ?
**RuntimeError: Error(s) in loading state_dict for ResNeXt**
Thanks.

**Comment by ahmetgunduz** [comment]
the codebase is updated. Could you please pull the repo and recheck ?

**Comment by Karthik-Bhaskar** [comment]
@MrXuf No, I could not resolve it. Recheck with updated codebase as @ahmetgunduz  told above.

**Comment by MrXuf** [comment]
Oh！Thank you for your email. I had the same problem and it bothered me for a few days. I will recheck latest code.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Karthik-Bhaskar"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月23日(星期六) 晚上10:48
收件人:&nbsp;"ahmetgunduz/Real-time-GesRec"<Real-time-GesRec@noreply.github.com&gt;;
抄送:&nbsp;"Mr_Xuf_qq_mail"<2640503128@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ahmetgunduz/Real-time-GesRec] cuda gpu device Error (#33)





 
@MrXuf No, I could not resolve it. Recheck with updated codebase as @ahmetgunduz  told above.

**Comment by niuwenju** [comment]
@MrXuf  Hi,have you resolve it?
