### ISSUE TITLE
Get stuck at running online_test.py with pretrained model on CPU

### ISSUE THREAD

**Issue by KKKKKyle** [ahmetgunduz/Real-time-GesRec#40]
I was trying to run oneline_test.py with pretrained model on CPU (w/o CUDA). I did some modification in model.py and online_test.py, including:

1. added `opt.no_cuda = True` right after `opt = parse_opts_online()`
2. added `map_location=torch.device('cpu')` to `torch.load(opt.pretrain_path)`
3. modified `model.load_state_dict(pretrain['state_dict'])`at line 120ish to     
```
            state_dict =pretrain['state_dict']
            from collections import OrderedDict
            new_state_dict = OrderedDict()
            for k, v in state_dict.items():
                if 'module' in k:
                    name = k[7:] # remove 'module.' of dataparallel
                new_state_dict[name]=v
            model.load_state_dict(new_state_dict)
```
Solved the issue of 

```
Missing key(s) in state_dict: "conv1.weight",...
Unexpected key(s) in state_dict: "module.conv1.weight", ...
```

[solved by looking into here]( https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686/12)

However, now it gives me an error:

```
Traceback (most recent call last):
  File "online_test.py", line 138, in <module>
    detector,classifier = load_models(opt)
  File "online_test.py", line 76, in load_models
    detector, parameters = generate_model(opt)
  File "...../Real-time-GesRec-master/model.py", line 132, in generate_model
    model.load_state_dict(new_state_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResNetL:
        size mismatch for conv1.weight: copying a param with shape torch.Size([16, 1, 7, 7, 7]) from checkpoint, the shape in current model is torch.Size([16, 3, 7, 7, 7]).
```

Thanks in advance!!!

**Comment by ahmetgunduz** [comment]
@KKKKKyle  could you please pull the latest version of the codebase and provide `pretrain_modality` parameter for the model being loaded.

**Comment by ttrungtin** [comment]
@ahmetgunduz  I pulled the latest version. I want to try on nvGesture dataset. I ran the annotation. And run the "run-nvgesture.sh" file but there were some different variables so I changed it myself. I create my own parser function based on the original one (default values also included). I use the pre-trained weight named "nv_resnext_101_Depth_32.pth". And got the same shape error with him. I am using Windows so the .sh file was complicated for me to run. That why I create a new parser function. Here is my parameter, I splited that parameters you might want to check. Thank you in advance!

`parser.add_argument('--pretrain_path', default='models/nv_resnext_101_Depth_32.pth', type=str, help='Pretrained model (.pth)')`
`parser.add_argument('--model', default='resnext', type=str, help='(resnet | preresnet | wideresnet | resnext | densenet | ')`
`parser.add_argument('--pretrain_modality', default='RGB', type=str, help='Modality of the pretrain model. RGB, Flow or RGBFlow')`
`parser.add_argument('--modality', default='RGB', type=str, help='Modality of generated model. RGB, Flow or RGBFlow')`

____________________________
`parser.add_argument('--root_path', default='', type=str, help='Root directory path of data')`
`parser.add_argument('--video_path', default='datasets/nvGesture', type=str, help='Directory path of Videos')`
`parser.add_argument('--annotation_path', default='annotation_nvGesture/nvall_but_None.json', type=str, help='Annotation file path')`
`parser.add_argument('--result_path', default='results/nvGesture', type=str, help='Result directory path')`
`parser.add_argument('--dataset', default='nvgesture', type=str, help='Used dataset (activitynet | kinetics | ucf101 | hmdb51)')`
`parser.add_argument('--n_classes', default=25, type=int, help='Number of classes (activitynet: 200, kinetics: 400, ucf101: 101, hmdb51: 51)')`
`parser.add_argument('--n_finetune_classes', default=26, type=int, help='Number of classes for fine-tuning. n_classes is set to the number when pretraining.')`
`parser.add_argument('--model_depth', default=101, type=int, help='Depth of resnet (10 | 18 | 34 | 50 | 101)')`
`parser.add_argument('--resnet_shortcut', default='A', type=str, help='Shortcut type of resnet (A | B)')`
`parser.add_argument('--resnext_cardinality', default=32, type=int, help='ResNeXt cardinality')`
`parser.add_argument('--sample_duration', default=16, type=int, help='Temporal duration of inputs')`
`parser.add_argument('--sample_size', default=112, type=int, help='Height and width of inputs')`
`parser.set_defaults(no_cuda=False)`
`parser.add_argument('--groups', default=3, type=int, help='The number of groups at group convolutions at conv layers')`
`parser.add_argument('--version', default=1.1, type=float, help='Version of the model')`
`parser.add_argument('--width_mult', default=3.0, type=float, help='The applied width multiplier to scale number of filters')`
`parser.add_argument('--train_crop', default='random', type=str, help='Spatial cropping method in training. random is uniform. corner is selection from 4 corners and 1 center.  (random | corner | center)')`
`parser.add_argument('--learning_rate', default=0.1, type=float, help='Initial learning rate (divided by 10 while training by lr scheduler)')`
`parser.add_argument('--downsample', default=2, type=int, help='Downsampling. Selecting 1 frame out of N')`
`parser.add_argument('--batch_size', default=2, type=int, help='Batch Size')`
`parser.add_argument('--n_threads', default=16, type=int, help='Number of threads for multi-thread loading')`
`parser.add_argument('--checkpoint', default=1, type=int, help='Trained model is saved at every this epochs.')`
`parser.add_argument('--n_val_samples', default=1, type=int, help='Number of validation samples for each activity')`
`parser.add_argument('--n_epochs', default=30, type=int, help='Number of total epochs to run')`
`parser.add_argument('--test_subset', default='test', type=str, help='Used subset in test (val | test)')`
`parser.add_argument('--ft_portion', default='last_layer', type=str, help='The portion of the model to apply fine tuning, either complete or last_layer')`
`parser.add_argument('--initial_scale', default=1.0, type=float, help='Initial scale for multiscale cropping')`
`parser.add_argument('--n_scales', default=5, type=int, help='Number of scales for multiscale cropping')`
`parser.add_argument('--scale_step', default=0.84089641525, type=float, help='Scale step for multiscale cropping')`
`parser.add_argument('--norm_value', default=1, type=int, help='If 1, range of inputs is [0-255]. If 255, range of inputs is [0-1].')`
`parser.add_argument('--mean_dataset', default='activitynet', type=str, help='dataset for mean values of mean subtraction (activitynet | kinetics)')`
`parser.add_argument('--manual_seed', default=1, type=int, help='Manually set random seed')`
