### ISSUE TITLE
Not able to run offline_test.py  for Jester dataset

### ISSUE THREAD

**Issue by joyalbin** [ahmetgunduz/Real-time-GesRec#41]
Thank you so much for the great solution.

I am in the processing validating the solution and understanding more. Tried to test the pretrained model `jester_resnext_101_RGB_32.pth` with `Jester` dataset

Downloaded dataset and performed frame creation with `python utils/jester_json.py 'annotation_Jester'`.

But the command `Python offline_test.py` is giving below error:
`dataset loading [14780/14787]
run
Traceback (most recent call last):
  File "offline_test.py", line 161, in <module>
    outputs = model(inputs)
  File "/home/albin/anaconda3/envs/l3c_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/albin/anaconda3/envs/l3c_env/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 146, in forward
    "them on device: {}".format(self.src_device_obj, t.device))
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu`

Please someone help me to resolve this issue

Regards,
Albin

**Comment by ahmetgunduz** [comment]
Hi @joyalbin, Could you please share your bash file? What parameter setting did you provide?

**Comment by joyalbin** [comment]
@ahmetgunduz 
I have am trying to run the pretrained model with Jester dataset for validation.

I have followed below steps:
1. Downloaded dataset and performed frame creation with `python utils/jester_json.py 'annotation_Jester'`
2.` Python offline_test.py` to run the test.

Do we have to run the `bash run_offline.sh`? This file take to the training flow right?
I am attaching the configuration in opt.py @ [opts.zip](https://github.com/ahmetgunduz/Real-time-GesRec/files/3834443/opts.zip)
I am also attaching all the changes I have done [changes.zip](https://github.com/ahmetgunduz/Real-time-GesRec/files/3834460/changes.zip)


Please let me know for any other clarification needed?

**Comment by joyalbin** [comment]
@ahmetgunduz ,

I have tried to run on CPU with the Jester dataset, but the output is looks something wrong
`[768/3721]      Time 4.36575 (4.43552)  prec@1 0.03231 prec@5 0.19214   precision 0.00000 (0.02187)     recall 0.00000 (0.02188)
[769/3721]      Time 4.35585 (4.43541)  prec@1 0.03227 prec@5 0.19221   precision 0.00000 (0.02184)     recall 0.00000 (0.02185)
[770/3721]      Time 4.66763 (4.43571)  prec@1 0.03222 prec@5 0.19196   precision 0.00000 (0.02181)     recall 0.00000 (0.02182)
[771/3721]      Time 4.63331 (4.43597)  prec@1 0.03218 prec@5 0.19188   precision 0.00000 (0.02178)     recall 0.00000 (0.02179)
[772/3721]      Time 4.72909 (4.43635)  prec@1 0.03214 prec@5 0.19171   precision 0.00000 (0.02175)     recall 0.00000 (0.02176)
[773/3721]      Time 4.66799 (4.43665)  prec@1 0.03218 prec@5 0.19211   precision 0.20000 (0.02199)     recall 0.05000 (0.02180)
[774/3721]      Time 4.76381 (4.43707)  prec@1 0.03222 prec@5 0.19234   precision 0.14286 (0.02214)     recall 0.03571 (0.02182)
[775/3721]      Time 4.69590 (4.43741)  prec@1 0.03218 prec@5 0.19242   precision 0.00000 (0.02211)     recall 0.00000 (0.02179)
[776/3721]      Time 4.77834 (4.43785)  prec@1 0.03214 prec@5 0.19249   precision 0.00000 (0.02208)     recall 0.00000 (0.02176)
[777/3721]      Time 4.60645 (4.43806)  prec@1 0.03209 prec@5 0.19257   precision 0.00000 (0.02206)     recall 0.00000 (0.02173)
[778/3721]      Time 4.67847 (4.43837)  prec@1 0.03213 prec@5 0.19256   precision 0.04762 (0.02209)     recall 0.03571 (0.02175)
[779/3721]      Time 4.74953 (4.43877)  prec@1 0.03209 prec@5 0.19231   precision 0.00000 (0.02206)     recall 0.00000 (0.02172)
[780/3721]      Time 4.61930 (4.43900)  prec@1 0.03205 prec@5 0.19215   precision 0.00000 (0.02203)     recall 0.00000 (0.02169)
[781/3721]      Time 4.74495 (4.43939)  prec@1 0.03201 prec@5 0.19198   precision 0.00000 (0.02200)     recall 0.00000 (0.02167)
[782/3721]      Time 4.42608 (4.43938)  prec@1 0.03197 prec@5 0.19198   precision 0.00000 (0.02198)     recall 0.00000 (0.02164)
[783/3721]      Time 4.34358 (4.43926)  prec@1 0.03193 prec@5 0.19181   precision 0.00000 (0.02195)     recall 0.00000 (0.02161)
[784/3721]      Time 4.55438 (4.43940)  prec@1 0.03189 prec@5 0.19165   precision 0.00000 (0.02192)     recall 0.00000 (0.02158)
`

The precision value are very small. Could you please let me know, does it expected?
Please helps to resolve the GPU execution issue also.

Regards,
Albin

**Comment by joyalbin** [comment]
@ahmetgunduz  I am able to run the test with Jester dataset. But the accuracy is poor. I will create another issue for that. Thank you

**Comment by xiaomingnio** [comment]
@joyalbin  how to solve the GPU issue?
