### ISSUE TITLE
RuntimeError: input and weight type

### ISSUE THREAD

**Issue by khasmamad99** [ahmetgunduz/Real-time-GesRec#48]
I am tyring train a detector on Jester dataset. However, when I run run_offline.sh I encounter the followring error right after the dataset is loaded:

Traceback (most recent call last):
  File "main.py", line 177, in <module>
    train_logger, train_batch_logger)
  File "/home/khasmamad/Desktop/kimo/Real-time-GesRec/train.py", line 34, in train_epoch
    outputs = model(inputs)
  File "/home/khasmamad/miniconda3/envs/gesrec/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/khasmamad/miniconda3/envs/gesrec/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/khasmamad/miniconda3/envs/gesrec/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/khasmamad/Desktop/kimo/Real-time-GesRec/models/resnetl.py", line 177, in forward
    x = self.conv1(x)
  File "/home/khasmamad/miniconda3/envs/gesrec/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/khasmamad/miniconda3/envs/gesrec/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 448, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

Googling showed me that this happens when the input and model are on separate devices (in this case, input is in GPU, while model is in CPU). But I still cannot figure out a solution. Please, help.

**Comment by khasmamad99** [comment]
This is how run_offline.sh looks like:
#!/bin/bash
python main.py \
	--root_path ~/Desktop/kimo/ \
	--video_path 20bn-jester-v1/ \
	--annotation_path Real-time-GesRec/annotation_Jester/jester.json \
	--result_path Real-time-GesRec/results \
	--dataset jester \
	--sample_duration 8 \
    --learning_rate 0.01 \
    --model resnetl \
	--model_depth 10 \
	--resnet_shortcut B \
	--batch_size 16 \
	--n_classes 2 \
	--n_threads 16 \
	--checkpoint 1 \
	--modality RGB \
	--train_crop random \
	--n_val_samples 1 \
	--test_subset test \
    --n_epochs 100 \
    --test \

**Comment by khasmamad99** [comment]
This modification fixed it (main.py line 66-68):

    model, parameters = generate_model(opt)
    model = model.cuda()
    print(model)

**Comment by wxjames** [comment]
Hi, may I ask about the accuracy of the detector? When I train the detector for EgoGesture, the accuracy is only about 0.5. It seems like the accuracy does not improve.

My code is like this:
python main.py \
	--root_path ~/ \
	--video_path /home/wisccitl/Desktop/EgoGesture \
	--annotation_path Real-time-GesRec/annotation_EgoGesture/egogesturebinary.json\
	--result_path Real-time-GesRec/results \
	--dataset egogesture \
	--sample_duration 8 \
  --learning_rate 0.1 \
  --model resnetl \
	--model_depth 10 \
	--resnet_shortcut A \
	--batch_size 8 \
	--n_classes 2 \
	--n_finetune_classes 2 \
	--n_threads 16 \
	--checkpoint 1 \
	--modality Depth \
	--train_crop random \
	--n_val_samples 1 \
	--test_subset test \
  --n_epochs 100 \

**Comment by ahmetgunduz** [comment]
that is akward. Can you check that if data is properly read?
