### ISSUE TITLE
egogesture_online.py--IndexError

### ISSUE THREAD

**Issue by susu1234567** [ahmetgunduz/Real-time-GesRec#49]
when I ran "online_test.py", the error-"IndexError index -3 is out of bounds for axis 0 with size 0" happened in the line 152 of egogesture_online.py
(counts = np.bincount(label_list[np.array(list(range(_    - int(sample_duration/8), _   )))])).
I do not know how to resolve it.

**Comment by ahmetgunduz** [comment]
You are probably providing wrong path parameters. It seems the data is not been read. Could you provide your parameter settings?

**Comment by susu1234567** [comment]
I use windows 10 not Ubuntu. The parameter settings are shown in 1.png (I run online_test.py not run_online.sh) and the error's details are shown in 2.png.

**Comment by susu1234567** [comment]
123

**Comment by susu1234567** [comment]
![123](https://user-images.githubusercontent.com/44127702/76140014-21b11800-6091-11ea-88b2-12b446e0846c.png)

**Comment by susu1234567** [comment]
![123](https://user-images.githubusercontent.com/44127702/76140050-810f2800-6091-11ea-8a65-2331dcf60ab6.png)

**Comment by susu1234567** [comment]
![123](https://user-images.githubusercontent.com/44127702/76140106-f2e77180-6091-11ea-8520-09ed8e99fb6e.png)

**Comment by susu1234567** [comment]
![123](https://user-images.githubusercontent.com/44127702/76140139-48bc1980-6092-11ea-8b56-fdb74f2016fe.png)

**Comment by susu1234567** [comment]
![1](https://user-images.githubusercontent.com/44127702/76140298-d815fc80-6093-11ea-907f-6858a5441560.png)

**Comment by susu1234567** [comment]
![2](https://user-images.githubusercontent.com/44127702/76140302-e237fb00-6093-11ea-927e-c9d93d98faed.png)

**Comment by susu1234567** [comment]
I use windows 10 not Ubuntu. The parameter settings are shown in 1.png (I run online_test.py not run_online.sh) and the error's details are shown in 2.png.

**Comment by susu1234567** [comment]
I use windows 10 not Ubuntu. The parameter settings and the error's details are shown in the 2 pictures.

**Comment by kinfeparty** [comment]
> I use windows 10 not Ubuntu. The parameter settings and the error's details are shown in the 2 pictures.

Hello, Have you fixed this question?

**Comment by kinfeparty** [comment]
@ahmetgunduz  Hello , I got the same question,I can test the result on Subject02/Scene4/Color/rgb3 ,which means my file-path is right.
Start Evaluation
[1/431]============
/Lun4/fdh/Real-time-GesRec/../egogesture-dataset/image/Subject02/Scene4/Color/rgb3
@@@@@@@@@@@@@@ Subject02/Scene4/Color/rgb3
[INFO]: Videot  is loading... /Lun4/fdh/Real-time-GesRec/../egogesture-dataset/image/Subject02/Scene4/Color/rgb3 Subject02/Scene4/Color/rgb3
Late Detected - class : 24 with prob : 0.18764839372066877 at frame 217                       [16/1813]
Late Detected - class : 20 with prob : 0.1577338852185688 at frame 336
Late Detected - class : 25 with prob : 0.30396864102929366 at frame 450
Late Detected - class : 21 with prob : 0.37977106170665753 at frame 558
Late Detected - class : 23 with prob : 0.5909073775384 at frame 660
Late Detected - class : 28 with prob : 0.4107779839943049 at frame 768Late Detected - class : 31 with prob : 0.40609707859294686 at frame 892
Late Detected - class : 26 with prob : 0.3792679342598525 at frame 999
Late Detected - class : 29 with prob : 0.5789668794707581 at frame 1105
Late Detected - class : 27 with prob : 0.4358846818839483 at frame 1195
Late Detected - class : 32 with prob : 0.5389359963364682 at frame 1274
Late Detected - class : 30 with prob : 0.5401946523930535 at frame 1357
predicted classes:       [22 24 20 25 21 23 28 31 26 29 27 32 30]
True classes :           [22 24 20 25 21 23 28 31 26 29 27 32 30]
Levenshtein Accuracy = 1.0 (1.0)

But  Subject02/Scene4/Color/rgb6 can't read .
[INFO]: Videot  is loading... /Lun4/fdh/Real-time-GesRec/../egogesture-dataset/image/Subject02/Scene4/Color/rgb6 Subject02/Scene4/Color/rgb6
Traceback (most recent call last):
  File "online_test.py", line 191, in <module>
    opt, spatial_transform, None, target_transform)
  File "/Lun4/fdh/Real-time-GesRec/dataset.py", line 201, in get_online_data
    sample_duration=opt.sample_duration)
  File "/Lun4/fdh/Real-time-GesRec/datasets/egogesture_online.py", line 206, in __init__
    annotation_path, video_path, whole_path, sample_duration,n_samples_for_each_video, stride_len)
  File "/Lun4/fdh/Real-time-GesRec/datasets/egogesture_online.py", line 153, in make_dataset
    counts = np.bincount(label_list[np.array(list(range(_    - int(sample_duration/8), _   )))])
IndexError: index 1238 is out of bounds for axis 1 with size 1238

I check this file in egogestureall.json 1238 is the end_file of one gesutre.
Subject02/Scene4/Color/rgb6 53 1198 1238

I do a test in online_test.py, I modify the code
”subject_list = ['Subject{:02d}'.format(i) for i in [2, 9, 11, 14, 18, 19, 28, 31, 41, 47]]“
to ”subject_list = ['Subject{:02d}'.format(i) for i in 14, 18, 19, 28, 31, 41, 47]]“
it appears the same bug.

[INFO]: Videot  is loading... /Lun4/fdh/Real-time-GesRec/../egogesture-dataset/image/Subject1[508/1813]
olor/rgb3 Subject14/Scene4/Color/rgb3
Traceback (most recent call last):
  File "online_test.py", line 192, in <module>
    opt, spatial_transform, None, target_transform)
  File "/Lun4/fdh/Real-time-GesRec/dataset.py", line 201, in get_online_data
    sample_duration=opt.sample_duration)
  File "/Lun4/fdh/Real-time-GesRec/datasets/egogesture_online.py", line 206, in __init__
    annotation_path, video_path, whole_path, sample_duration,n_samples_for_each_video, stride_len)
  File "/Lun4/fdh/Real-time-GesRec/datasets/egogesture_online.py", line 153, in make_dataset
    counts = np.bincount(label_list[np.array(list(range(_    - int(sample_duration/8), _   )))])
IndexError: index 1250 is out of bounds for axis 1 with size 1250

Can you help me fix this strange bug?

**Comment by b0ssplz** [comment]
@susu1234567 Have you fixed this? I also have this error and don't know what to do.

**Comment by fweidner** [comment]
Hi,

I encountered the issue on Windows10. In egogesture_online.py, line 106 I had to make the following changes:

Old:
```
def get_annotation(data, whole_path):
    annotation = []
    print("@@@@@@@@@@@@@@", whole_path)

    for key, value in data['database'].items():
        if key.split('_')[0] == whole_path:
            annotation.append(value['annotations'])

    return  annotation

```

New:
```
def get_annotation(data, whole_path):
    annotation = []
    print("@@@@@@@@@@@@@@", whole_path)

    for key, value in data['database'].items():
        tmp_whole_path = whole_path.replace("\\", "/")
        if key.split('_')[0] == tmp_whole_path:
            annotation.append(value['annotations'])

    return  annotation
```

**Comment by xiaoxingf** [comment]
> **@ahmetgunduz Hello , I got the same question,I can test the result on Subject02/Scene4/Color/rgb3 ,which means my file-path is right.**
> Start Evaluation
> [1/431]============
> /Lun4/fdh/Real-time-GesRec/../egogesture-dataset/image/Subject02/Scene4/Color/rgb3
> @@@@@@@@@@@@@@ Subject02/Scene4/Color/rgb3
> [INFO]: Videot is loading... /Lun4/fdh/Real-time-GesRec/../egogesture-dataset/image/Subject02/Scene4/Color/rgb3 Subject02/Scene4/Color/rgb3
> Late Detected - class : 24 with prob : 0.18764839372066877 at frame 217 [16/1813]
> Late Detected - class : 20 with prob : 0.1577338852185688 at frame 336
> Late Detected - class : 25 with prob : 0.30396864102929366 at frame 450
> Late Detected - class : 21 with prob : 0.37977106170665753 at frame 558
> Late Detected - class : 23 with prob : 0.5909073775384 at frame 660
> Late Detected - class : 28 with prob : 0.4107779839943049 at frame 768Late Detected - class : 31 with prob : 0.40609707859294686 at frame 892
> Late Detected - class : 26 with prob : 0.3792679342598525 at frame 999
> Late Detected - class : 29 with prob : 0.5789668794707581 at frame 1105
> Late Detected - class : 27 with prob : 0.4358846818839483 at frame 1195
> Late Detected - class : 32 with prob : 0.5389359963364682 at frame 1274
> Late Detected - class : 30 with prob : 0.5401946523930535 at frame 1357
> predicted classes: [22 24 20 25 21 23 28 31 26 29 27 32 30]
> True classes : [22 24 20 25 21 23 28 31 26 29 27 32 30]
> Levenshtein Accuracy = 1.0 (1.0)
> 
> **But Subject02/Scene4/Color/rgb6 can't read .**
> [INFO]: Videot is loading... /Lun4/fdh/Real-time-GesRec/../egogesture-dataset/image/Subject02/Scene4/Color/rgb6 Subject02/Scene4/Color/rgb6
> Traceback (most recent call last):
> File "online_test.py", line 191, in
> opt, spatial_transform, None, target_transform)
> File "/Lun4/fdh/Real-time-GesRec/dataset.py", line 201, in get_online_data
> sample_duration=opt.sample_duration)
> File "/Lun4/fdh/Real-time-GesRec/datasets/egogesture_online.py", line 206, in **init**
> annotation_path, video_path, whole_path, sample_duration,n_samples_for_each_video, stride_len)
> File "/Lun4/fdh/Real-time-GesRec/datasets/egogesture_online.py", line 153, in make_dataset
> counts = np.bincount(label_list[np.array(list(range(_ - int(sample_duration/8), _ )))])
> IndexError: index 1238 is out of bounds for axis 1 with size 1238
> 
> **I check this file in egogestureall.json 1238 is the end_file of one gesutre. Subject02/Scene4/Color/rgb6 53 1198 1238**
> 
> **I do a test in online_test.py, I modify the code ”subject_list = ['Subject{:02d}'.format(i) for i in [2, 9, 11, 14, 18, 19, 28, 31, 41, 47]]“ to ”subject_list = ['Subject{:02d}'.format(i) for i in 14, 18, 19, 28, 31, 41, 47]]“ it appears the same bug.**
> 
> [INFO]: Videot is loading... /Lun4/fdh/Real-time-GesRec/../egogesture-dataset/image/Subject1[508/1813]
> olor/rgb3 Subject14/Scene4/Color/rgb3
> Traceback (most recent call last):
> File "online_test.py", line 192, in
> opt, spatial_transform, None, target_transform)
> File "/Lun4/fdh/Real-time-GesRec/dataset.py", line 201, in get_online_data
> sample_duration=opt.sample_duration)
> File "/Lun4/fdh/Real-time-GesRec/datasets/egogesture_online.py", line 206, in **init**
> annotation_path, video_path, whole_path, sample_duration,n_samples_for_each_video, stride_len)
> File "/Lun4/fdh/Real-time-GesRec/datasets/egogesture_online.py", line 153, in make_dataset
> counts = np.bincount(label_list[np.array(list(range(_ - int(sample_duration/8), _ )))])
> IndexError: index 1250 is out of bounds for axis 1 with size 1250
> 
> **Can you help me fix this strange bug?**

hello,did you resolved this qustion?

**Comment by xiaoxingf** [comment]
I also encountered the problem.Its because the generated json annotation file lack a "None" gesture annotation for the last frames of every video.
for example ,I add' "Subject02/Scene2/Color/rgb3_218": {"subset": "testing", "annotations": {"label": "None", "start_frame": "1418", "end_frame": "1549"}}, 'in the json file,then for testing 'Subject02/Scene2/Color/rgb3' video ,it will right.
![2021-01-16 20-41-50屏幕截图](https://user-images.githubusercontent.com/51583088/104812188-8d304e00-583b-11eb-97ff-6b51e2d094e6.png)
